name: default

kind: pipeline
type: docker

steps:
- name: build
  image: gradle:6.0.1
  environment:
    GPR_USER:
      from_secret: gpr_user
    GPR_API_KEY:
      from_secret: gpr_key
  commands:
    - gradle -x functionTest clean build
    - gradle publishGprPublicationToGitHubPackagesRepository
  when:
    branch:
    - develop

- name: release
  image: gradle:6.0.1
  environment:
    GPR_USER:
      from_secret: gpr_user
    GPR_API_KEY:
      from_secret: gpr_key
    GRADLE_PUBLISH_KEY:
      from_secret: gradlePublishKey
    GRADLE_PUBLISH_SECRET:
      from_secret: gradlePublishSecret
  commands:
    - gradle -x functionTest clean build
    - gradle publishGprPublicationToGitHubPackagesRepository -PpublishVersion=$DRONE_TAG
    - gradle publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET -PpublishVersion=$DRONE_TAG
  when:
    branch:
    - master
    ref:
    - refs/tags/*