name: default

kind: pipeline
type: docker

steps:
- name: gradle-builder
  image: gradle
  commands:
    - gradle -x test clean build
    - gradle publishPlugins -Pgradle.publish.key=$gradlePublishKey -Pgradle.publish.secret=$gradlePublishSecret
