name: default

kind: pipeline
type: docker

steps:
- name: gradle-builder
  image: gradle
  commands:
    - gradle clean build
    - gradle publishPlugins -Pgradle.publish.key=${gradlePublishKey} -Pgradle.publish.secret=${gradlePublishSecret
