name: default

kind: pipeline
type: docker

steps:
- name: gradle-builder
  image: gradle
  commands:
    - gradle -x functionTest clean build
    - gradle publishPlugins -Dgradle.publish.key=$gradlePublishKey -Dgradle.publish.secret=$gradlePublishSecret
