name: default

kind: pipeline
type: docker

steps:
- name: gradle-builder
  image: gradle
  environment:
    GRADLE_PUBLISH_KEY:
      from_secret: gradlePublishKey
    GRADLE_PUBLISH_SECRET:
      from_secret: gradlePublishSecret
  commands:
    - gradle -x functionTest clean build
    - gradle publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
