/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.artificerpi;

import static org.junit.Assert.assertNotNull;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Ignore;
import org.junit.Test;

/**
 * A simple unit test for the 'io.github.artificerpi.greeting' plugin.
 */
public class SpringAutoAsciidocPluginTest {
  @Ignore
  @Test
  public void pluginRegistersATask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("io.github.artificerpi.spring-auto-asciidoc");

    // Verify the result
    assertNotNull(project.getTasks().findByName("asciidocTemplate"));
  }
}
